baseURL = "https://sloth.dev/"
title = "Sloth"
theme = "hugo-geekdoc"
languageCode = "en-us"
pluralizeListTitles = false

# Disable so the version of hugo is not set on the html and generating the docs with
# different versions always fail because of the metadata.
disableHugoGeneratorInject = true

publishDir = "./docs"

[params]
  geekdocLogo = "media/sloth-logo-white.svg"

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   tag = "tags"
