baseURL = "https://sloth.dev/"
title = "Sloth"
theme = "hugo-geekdoc"
languageCode = "en-us"
pluralizeListTitles = false

# Disable so the version of hugo is not set on the html and generating the docs with
# different versions always fail because of the metadata.
disableHugoGeneratorInject = true

googleAnalytics = "G-MGXZFGF3VJ"

publishDir = "./docs"

[params]
  geekdocLogo = "media/sloth-logo-white.svg"
  favicon = "/media/favicon.ico"

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[markup]
  [markup.highlight]
    codeFences = false
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "dracula"
    tabWidth = 4
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   tag = "tags"
